[package]
name = "tag"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2021"

[dependencies]
ansi_term = "^0.12"
id3 = "0.6"
regex = "^1.0"
walkdir = "^2.0"

[dependencies.clap]
version = "3.0"
features = ["derive"]
