[package]
name = "tag"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2021"

[dependencies]
nu-ansi-term = "0.46"
id3 = "1.0"
regex = "^1.0"
walkdir = "^2.0"

[dependencies.clap]
version = "4.0"
features = ["derive"]
