[package]
name = "tag"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2018"

[dependencies]
id3 = "^0.3"
docopt = "^1.0"
serde = "^1.0"
serde_derive = "^1.0"
walkdir = "^2.0"
regex = "^1.0"
ansi_term = "^0.12"

[dependencies.clippy]
version = "*"
optional = true
